<?php 
/**
	Admin Page Framework v3.8.15 by Michael Uno 
	Generated by PHP Class Files Script Generator <https://github.com/michaeluno/PHP-Class-Files-Script-Generator>
	<http://en.michaeluno.jp/seur>
	Copyright (c) 2013-2017, Michael Uno; Licensed under MIT <http://opensource.org/licenses/MIT> */
class SEUR_AdminPageFramework_Form_View___CSS_term_meta extends SEUR_AdminPageFramework_Form_View___CSS_Base {
    protected function _get() {
        return $this->_getRules();
    }
    private function _getRules() {
        return ".seur-form-table-outer-row-term_meta,.seur-form-table-outer-row-term_meta > td {margin: 0;padding: 0;}.seur-form-table-term_meta > tbody > tr > td {margin-left: 0;padding-left: 0;}.seur-form-table-term_meta .seur-sectionset,.seur-form-table-term_meta .seur-section {margin-bottom: 0;}.seur-form-table-term_meta.add-new-term .title-colon {margin-left: 0.2em;}.seur-form-table-term_meta.add-new-term .seur-section .form-table > tbody > tr > td,.seur-form-table-term_meta.add-new-term .seur-section .form-table > tbody > tr > th{display: inline-block;width: 100%;padding: 0;float: right;clear: right;}.seur-form-table-term_meta.add-new-term .seur-field {width: auto;}.seur-form-table-term_meta.add-new-term .seur-field {max-width: 100%;}.seur-form-table-term_meta.add-new-term .sortable .seur-field {width: auto;} .seur-form-table-term_meta.add-new-term .seur-section .form-table > tbody > tr > th {font-size: 13px;line-height: 1.5;margin: 0;font-weight: 700;}.seur-form-table-term_meta .seur-section-title h3 {border: none;font-weight: bold;font-size: 1.12em;margin: 0;padding: 0;font-family: 'Open Sans', sans-serif; cursor: inherit; -webkit-user-select: inherit;-moz-user-select: inherit;user-select: inherit;}.seur-form-table-term_meta .seur-collapsible-title h3 {margin: 0;}.seur-form-table-term_meta h4 {margin: 1em 0;font-size: 1.04em;}.seur-form-table-term_meta .seur-section-tab h4 {margin: 0;} ";
    }
}
